import{S as c,i as u}from"./assets/vendor-0fc460d7.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();function f(e,s){const o="https://pixabay.com/api/",n=new URLSearchParams({key:"44177733-63c355e78480ae17b664c6dfc",q:e,flower:s,image_type:"photo",orientation:"horizontal",safesearch:"true"}),t=`${o}?${n}`;return fetch(t).then(r=>{if(!r)throw new Error(r.statusText);return r.json()})}document.querySelector(".gallery");function m(e){return`<li class="img-item">
    <a class="img-link" href="${e.largeImageURL}">
    <img class="image" src="${e.webformatURL}" alt="${e.tags}"></a>
<div class="img-info">
    <p class="info"><b>Likes</b> ${e.likes}</p>
    <p class="info"><b>Views</b> ${e.views}</p>
    <p class="info"><b>Comments</b> ${e.comments}</p>
    <p class="info"><b>Downloads</b> ${e.downloads}</p>
   </div>
    </li>`}function d(e){return e.map(m).join("")}function p(){new c(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}const y=document.querySelector(".form"),a=document.querySelector(".gallery"),l=document.querySelector(".loader");y.addEventListener("submit",e=>{e.preventDefault(),a.innerHTML="",g();const s=e.target.elements.query.value.trim();f(s).then(o=>{if(o.hits.length===0){u.error({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#FAFAFB",color:"#EF4040",position:"topRight"});return}else{const n=d(o.hits);a.innerHTML=n,p()}}).catch(o=>console.log(o)).finally(()=>{e.target.reset(),h()})});function g(){l.style.display="block"}function h(){l.style.display="none"}
//# sourceMappingURL=commonHelpers.js.map
